# Generated by Django 4.1.7 on 2023-07-17 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfapp', '0003_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
