# Generated by Django 4.1.7 on 2023-07-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfapp', '0004_delete_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('recipe_image', models.ImageField(upload_to='recipes')),
                ('recipe_making', models.TextField()),
            ],
        ),
    ]
